package com.pride.summoner_searcher_api.model

import jakarta.persistence.*
import java.time.LocalDateTime

/**
 * Represents a user entity in the application's database.
 * This class is mapped to the "users" table in the PostgreSQL database.
 *
 * @property id The unique identifier for the user.
 * @property email The user's email address, used for login. Must be unique.
 * @property password The user's hashed password.
 * @property darkmodePreference The user's preference for dark mode on the frontend.
 * @property verified Flag indicating if the user has verified their email address.
 * @property verificationToken A temporary token sent to the user's email for account verification.
 * @property verificationTokenExpiry The expiration date for the verification token.
 * @property passwordResetToken A temporary token for resetting the user's password.
 * @property passwordResetTokenExpiry The expiration date for the password reset token.
 * @property twoFactorEnabled Flag indicating if the user has enabled Two-Factor Authentication.
 * @property twoFactorSecret The encrypted 2FA secret key for the user.
 * @property recentSearches A list of the user's recent search queries. Stored in a separate table.
 */
@Entity
@Table(name = "users") // Specifies the table name in the database.
data class User(
    @Id // Marks this field as the primary key.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the ID to be auto-generated by the database.
    val id: Long = 0,

    @Column(unique = true, nullable = false)
    var email: String,

    @Column(nullable = false)
    var password: String,

    @Column(nullable = false)
    var darkmodePreference: Boolean = false,

    @Column(nullable = false)
    var verified: Boolean = false,

    @Column(unique = true)
    var verificationToken: String? = null,

    var verificationTokenExpiry: LocalDateTime? = null,

    @Column(unique = true)
    var passwordResetToken: String? = null,

    var passwordResetTokenExpiry: LocalDateTime? = null,

    @Column(nullable = false)
    var twoFactorEnabled: Boolean = false,

    // This secret is encrypted before being stored in the database.
    var twoFactorSecret: String? = null,

    // This annotation maps the list to a separate table `user_recent_searches`.
    // FetchType.EAGER means recent searches are always loaded with the user.
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "user_recent_searches", joinColumns = [JoinColumn(name = "user_id")])
    @Column(name = "search_query")
    var recentSearches: MutableList<String> = mutableListOf()
)
