package com.pride.summoner_searcher_api.model

import jakarta.persistence.*
import org.springframework.security.core.GrantedAuthority
import org.springframework.security.core.userdetails.UserDetails
import java.time.LocalDateTime

/**
 * Represents a user entity in the application's database.
 * This class implements Spring Security's UserDetails interface, allowing it to be used
 * directly as the principal object in the security context.
 *
 * It is a regular `class` (not a `data class`) to have full control over the implementation
 * of UserDetails methods and avoid potential JVM signature clashes with auto-generated methods.
 */
@Entity
@Table(name = "users")
class User(
    /** The unique identifier for the user, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0,

    /** The user's email address, used for login and as the principal's name. */
    @Column(unique = true, nullable = false)
    var email: String,

    /**
     * The user's password, stored as a BCrypt hash.
     * This property is explicitly named `hashedPassword` to avoid a JVM signature clash
     * with the `getPassword()` method required by the `UserDetails` interface.
     */
    @Column(name = "password", nullable = false)
    var hashedPassword: String,

    /** The user's preference for dark mode on the frontend. */
    @Column(nullable = false)
    var darkmodePreference: Boolean = false,

    /** A flag indicating if the user has verified their email address. */
    @Column(nullable = false)
    var verified: Boolean = false,

    /** A temporary, unique token sent to the user's email for account verification. */
    @Column(unique = true)
    var verificationToken: String? = null,

    /** The expiration date and time for the verification token. */
    var verificationTokenExpiry: LocalDateTime? = null,

    /** A temporary, unique token for resetting the user's password. */
    @Column(unique = true)
    var passwordResetToken: String? = null,

    /** The expiration date and time for the password reset token. */
    var passwordResetTokenExpiry: LocalDateTime? = null,

    /** A flag indicating if the user has enabled Two-Factor Authentication. */
    @Column(nullable = false)
    var twoFactorEnabled: Boolean = false,

    /** The encrypted 2FA secret key for the user, used to verify authentication codes. */
    var twoFactorSecret: String? = null,

    /** User role for authorization (USER or ADMIN). Defaults to USER for regular users. */
    @Column(nullable = false, length = 20, columnDefinition = "VARCHAR(20) DEFAULT 'USER'")
    var role: String = "USER",

    /** A list of the user's recent search queries. Stored in a separate `user_recent_searches` table. */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "user_recent_searches", joinColumns = [JoinColumn(name = "user_id")])
    var recentSearches: MutableList<RecentSearch> = mutableListOf()

) : UserDetails {
    
    // --- UserDetails Implementation ---

    /** Returns the authorities granted to the user. For now, this is an empty list as we don't use roles. */
    override fun getAuthorities(): Collection<GrantedAuthority> = emptyList()

    /** Returns the user's hashed password. This delegates to the `hashedPassword` property. */
    override fun getPassword(): String = this.hashedPassword

    /** Returns the user's username. In this application, we use the email as the username. */
    override fun getUsername(): String = this.email

    /** Indicates whether the user's account has expired. An expired account cannot be authenticated. */
    override fun isAccountNonExpired(): Boolean = true // Accounts never expire in this app.

    /** Indicates whether the user is locked or unlocked. A locked user cannot be authenticated. */
    override fun isAccountNonLocked(): Boolean = true // Users are never locked in this app.

    /** Indicates whether the user's credentials (password) has expired. */
    override fun isCredentialsNonExpired(): Boolean = true // Credentials never expire.

    /**
     * Indicates whether the user is enabled or disabled.
     * We have decoupled this from the `verified` flag to allow custom error messages in the controller.
     * Spring Security will not block login based on this, so we must check `verified` manually.
     */
    override fun isEnabled(): Boolean = true
}
